//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("invidiadbModel", "FK_ResumeContents_Resumes", "Resume", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(iTestService.Resume), "ResumeContent", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(iTestService.ResumeContent), true)]

#endregion

namespace iTestService
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class invidiadbEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new invidiadbEntities object using the connection string found in the 'invidiadbEntities' section of the application configuration file.
        /// </summary>
        public invidiadbEntities() : base("name=invidiadbEntities", "invidiadbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new invidiadbEntities object.
        /// </summary>
        public invidiadbEntities(string connectionString) : base(connectionString, "invidiadbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new invidiadbEntities object.
        /// </summary>
        public invidiadbEntities(EntityConnection connection) : base(connection, "invidiadbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Candidate> Candidates
        {
            get
            {
                if ((_Candidates == null))
                {
                    _Candidates = base.CreateObjectSet<Candidate>("Candidates");
                }
                return _Candidates;
            }
        }
        private ObjectSet<Candidate> _Candidates;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Area> Areas
        {
            get
            {
                if ((_Areas == null))
                {
                    _Areas = base.CreateObjectSet<Area>("Areas");
                }
                return _Areas;
            }
        }
        private ObjectSet<Area> _Areas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Company> Companies
        {
            get
            {
                if ((_Companies == null))
                {
                    _Companies = base.CreateObjectSet<Company>("Companies");
                }
                return _Companies;
            }
        }
        private ObjectSet<Company> _Companies;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CandidateRole> CandidateRoles
        {
            get
            {
                if ((_CandidateRoles == null))
                {
                    _CandidateRoles = base.CreateObjectSet<CandidateRole>("CandidateRoles");
                }
                return _CandidateRoles;
            }
        }
        private ObjectSet<CandidateRole> _CandidateRoles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Status> Statuses
        {
            get
            {
                if ((_Statuses == null))
                {
                    _Statuses = base.CreateObjectSet<Status>("Statuses");
                }
                return _Statuses;
            }
        }
        private ObjectSet<Status> _Statuses;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ResumeContent> ResumeContents
        {
            get
            {
                if ((_ResumeContents == null))
                {
                    _ResumeContents = base.CreateObjectSet<ResumeContent>("ResumeContents");
                }
                return _ResumeContents;
            }
        }
        private ObjectSet<ResumeContent> _ResumeContents;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Resume> Resumes
        {
            get
            {
                if ((_Resumes == null))
                {
                    _Resumes = base.CreateObjectSet<Resume>("Resumes");
                }
                return _Resumes;
            }
        }
        private ObjectSet<Resume> _Resumes;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Candidates EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCandidates(Candidate candidate)
        {
            base.AddObject("Candidates", candidate);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Areas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAreas(Area area)
        {
            base.AddObject("Areas", area);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Companies EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCompanies(Company company)
        {
            base.AddObject("Companies", company);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CandidateRoles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCandidateRoles(CandidateRole candidateRole)
        {
            base.AddObject("CandidateRoles", candidateRole);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Statuses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStatuses(Status status)
        {
            base.AddObject("Statuses", status);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ResumeContents EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToResumeContents(ResumeContent resumeContent)
        {
            base.AddObject("ResumeContents", resumeContent);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Resumes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToResumes(Resume resume)
        {
            base.AddObject("Resumes", resume);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="invidiadbModel", Name="Area")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Area : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Area object.
        /// </summary>
        /// <param name="areasId">Initial value of the AreasId property.</param>
        /// <param name="username">Initial value of the Username property.</param>
        /// <param name="xml">Initial value of the Xml property.</param>
        public static Area CreateArea(global::System.Int32 areasId, global::System.String username, global::System.String xml)
        {
            Area area = new Area();
            area.AreasId = areasId;
            area.Username = username;
            area.Xml = xml;
            return area;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AreasId
        {
            get
            {
                return _AreasId;
            }
            set
            {
                if (_AreasId != value)
                {
                    OnAreasIdChanging(value);
                    ReportPropertyChanging("AreasId");
                    _AreasId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AreasId");
                    OnAreasIdChanged();
                }
            }
        }
        private global::System.Int32 _AreasId;
        partial void OnAreasIdChanging(global::System.Int32 value);
        partial void OnAreasIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                OnUsernameChanging(value);
                ReportPropertyChanging("Username");
                _Username = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Username");
                OnUsernameChanged();
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Xml
        {
            get
            {
                return _Xml;
            }
            set
            {
                OnXmlChanging(value);
                ReportPropertyChanging("Xml");
                _Xml = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Xml");
                OnXmlChanged();
            }
        }
        private global::System.String _Xml;
        partial void OnXmlChanging(global::System.String value);
        partial void OnXmlChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="invidiadbModel", Name="Candidate")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Candidate : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Candidate object.
        /// </summary>
        /// <param name="candidateID">Initial value of the CandidateID property.</param>
        /// <param name="username">Initial value of the Username property.</param>
        public static Candidate CreateCandidate(global::System.Guid candidateID, global::System.String username)
        {
            Candidate candidate = new Candidate();
            candidate.CandidateID = candidateID;
            candidate.Username = username;
            return candidate;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid CandidateID
        {
            get
            {
                return _CandidateID;
            }
            set
            {
                if (_CandidateID != value)
                {
                    OnCandidateIDChanging(value);
                    ReportPropertyChanging("CandidateID");
                    _CandidateID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CandidateID");
                    OnCandidateIDChanged();
                }
            }
        }
        private global::System.Guid _CandidateID;
        partial void OnCandidateIDChanging(global::System.Guid value);
        partial void OnCandidateIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                OnUsernameChanging(value);
                ReportPropertyChanging("Username");
                _Username = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Username");
                OnUsernameChanged();
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> RegistrationDate
        {
            get
            {
                return _RegistrationDate;
            }
            set
            {
                OnRegistrationDateChanging(value);
                ReportPropertyChanging("RegistrationDate");
                _RegistrationDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RegistrationDate");
                OnRegistrationDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _RegistrationDate;
        partial void OnRegistrationDateChanging(Nullable<global::System.DateTime> value);
        partial void OnRegistrationDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MailEntryID
        {
            get
            {
                return _MailEntryID;
            }
            set
            {
                OnMailEntryIDChanging(value);
                ReportPropertyChanging("MailEntryID");
                _MailEntryID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MailEntryID");
                OnMailEntryIDChanged();
            }
        }
        private global::System.String _MailEntryID;
        partial void OnMailEntryIDChanging(global::System.String value);
        partial void OnMailEntryIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CandidateNumber
        {
            get
            {
                return _CandidateNumber;
            }
            set
            {
                OnCandidateNumberChanging(value);
                ReportPropertyChanging("CandidateNumber");
                _CandidateNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CandidateNumber");
                OnCandidateNumberChanged();
            }
        }
        private Nullable<global::System.Int32> _CandidateNumber;
        partial void OnCandidateNumberChanging(Nullable<global::System.Int32> value);
        partial void OnCandidateNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IdentityNumber
        {
            get
            {
                return _IdentityNumber;
            }
            set
            {
                OnIdentityNumberChanging(value);
                ReportPropertyChanging("IdentityNumber");
                _IdentityNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IdentityNumber");
                OnIdentityNumberChanged();
            }
        }
        private global::System.String _IdentityNumber;
        partial void OnIdentityNumberChanging(global::System.String value);
        partial void OnIdentityNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateOfBirth
        {
            get
            {
                return _DateOfBirth;
            }
            set
            {
                OnDateOfBirthChanging(value);
                ReportPropertyChanging("DateOfBirth");
                _DateOfBirth = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateOfBirth");
                OnDateOfBirthChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateOfBirth;
        partial void OnDateOfBirthChanging(Nullable<global::System.DateTime> value);
        partial void OnDateOfBirthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsActive;
        partial void OnIsActiveChanging(Nullable<global::System.Boolean> value);
        partial void OnIsActiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Events
        {
            get
            {
                return _Events;
            }
            set
            {
                OnEventsChanging(value);
                ReportPropertyChanging("Events");
                _Events = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Events");
                OnEventsChanged();
            }
        }
        private global::System.String _Events;
        partial void OnEventsChanging(global::System.String value);
        partial void OnEventsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ResumePath
        {
            get
            {
                return _ResumePath;
            }
            set
            {
                OnResumePathChanging(value);
                ReportPropertyChanging("ResumePath");
                _ResumePath = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ResumePath");
                OnResumePathChanged();
            }
        }
        private global::System.String _ResumePath;
        partial void OnResumePathChanging(global::System.String value);
        partial void OnResumePathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> Experience
        {
            get
            {
                return _Experience;
            }
            set
            {
                OnExperienceChanging(value);
                ReportPropertyChanging("Experience");
                _Experience = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Experience");
                OnExperienceChanged();
            }
        }
        private Nullable<global::System.Int16> _Experience;
        partial void OnExperienceChanging(Nullable<global::System.Int16> value);
        partial void OnExperienceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Areas
        {
            get
            {
                return _Areas;
            }
            set
            {
                OnAreasChanging(value);
                ReportPropertyChanging("Areas");
                _Areas = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Areas");
                OnAreasChanged();
            }
        }
        private global::System.String _Areas;
        partial void OnAreasChanging(global::System.String value);
        partial void OnAreasChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Roles
        {
            get
            {
                return _Roles;
            }
            set
            {
                OnRolesChanging(value);
                ReportPropertyChanging("Roles");
                _Roles = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Roles");
                OnRolesChanged();
            }
        }
        private global::System.String _Roles;
        partial void OnRolesChanging(global::System.String value);
        partial void OnRolesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Mobile
        {
            get
            {
                return _Mobile;
            }
            set
            {
                OnMobileChanging(value);
                ReportPropertyChanging("Mobile");
                _Mobile = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Mobile");
                OnMobileChanged();
            }
        }
        private global::System.String _Mobile;
        partial void OnMobileChanging(global::System.String value);
        partial void OnMobileChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EMailAddress
        {
            get
            {
                return _EMailAddress;
            }
            set
            {
                OnEMailAddressChanging(value);
                ReportPropertyChanging("EMailAddress");
                _EMailAddress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EMailAddress");
                OnEMailAddressChanged();
            }
        }
        private global::System.String _EMailAddress;
        partial void OnEMailAddressChanging(global::System.String value);
        partial void OnEMailAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SentToCompanies
        {
            get
            {
                return _SentToCompanies;
            }
            set
            {
                OnSentToCompaniesChanging(value);
                ReportPropertyChanging("SentToCompanies");
                _SentToCompanies = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SentToCompanies");
                OnSentToCompaniesChanged();
            }
        }
        private global::System.String _SentToCompanies;
        partial void OnSentToCompaniesChanging(global::System.String value);
        partial void OnSentToCompaniesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Former8200
        {
            get
            {
                return _Former8200;
            }
            set
            {
                OnFormer8200Changing(value);
                ReportPropertyChanging("Former8200");
                _Former8200 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Former8200");
                OnFormer8200Changed();
            }
        }
        private Nullable<global::System.Boolean> _Former8200;
        partial void OnFormer8200Changing(Nullable<global::System.Boolean> value);
        partial void OnFormer8200Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Reference
        {
            get
            {
                return _Reference;
            }
            set
            {
                OnReferenceChanging(value);
                ReportPropertyChanging("Reference");
                _Reference = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Reference");
                OnReferenceChanged();
            }
        }
        private global::System.String _Reference;
        partial void OnReferenceChanging(global::System.String value);
        partial void OnReferenceChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="invidiadbModel", Name="CandidateRole")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CandidateRole : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CandidateRole object.
        /// </summary>
        /// <param name="roleId">Initial value of the RoleId property.</param>
        public static CandidateRole CreateCandidateRole(global::System.Int32 roleId)
        {
            CandidateRole candidateRole = new CandidateRole();
            candidateRole.RoleId = roleId;
            return candidateRole;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RoleId
        {
            get
            {
                return _RoleId;
            }
            set
            {
                if (_RoleId != value)
                {
                    OnRoleIdChanging(value);
                    ReportPropertyChanging("RoleId");
                    _RoleId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RoleId");
                    OnRoleIdChanged();
                }
            }
        }
        private global::System.Int32 _RoleId;
        partial void OnRoleIdChanging(global::System.Int32 value);
        partial void OnRoleIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                OnUsernameChanging(value);
                ReportPropertyChanging("Username");
                _Username = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Username");
                OnUsernameChanged();
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Xml
        {
            get
            {
                return _Xml;
            }
            set
            {
                OnXmlChanging(value);
                ReportPropertyChanging("Xml");
                _Xml = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Xml");
                OnXmlChanged();
            }
        }
        private global::System.String _Xml;
        partial void OnXmlChanging(global::System.String value);
        partial void OnXmlChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="invidiadbModel", Name="Company")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Company : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Company object.
        /// </summary>
        /// <param name="companiesID">Initial value of the CompaniesID property.</param>
        /// <param name="username">Initial value of the Username property.</param>
        /// <param name="xml">Initial value of the Xml property.</param>
        public static Company CreateCompany(global::System.Int32 companiesID, global::System.String username, global::System.String xml)
        {
            Company company = new Company();
            company.CompaniesID = companiesID;
            company.Username = username;
            company.Xml = xml;
            return company;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CompaniesID
        {
            get
            {
                return _CompaniesID;
            }
            set
            {
                if (_CompaniesID != value)
                {
                    OnCompaniesIDChanging(value);
                    ReportPropertyChanging("CompaniesID");
                    _CompaniesID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CompaniesID");
                    OnCompaniesIDChanged();
                }
            }
        }
        private global::System.Int32 _CompaniesID;
        partial void OnCompaniesIDChanging(global::System.Int32 value);
        partial void OnCompaniesIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                OnUsernameChanging(value);
                ReportPropertyChanging("Username");
                _Username = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Username");
                OnUsernameChanged();
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Xml
        {
            get
            {
                return _Xml;
            }
            set
            {
                OnXmlChanging(value);
                ReportPropertyChanging("Xml");
                _Xml = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Xml");
                OnXmlChanged();
            }
        }
        private global::System.String _Xml;
        partial void OnXmlChanging(global::System.String value);
        partial void OnXmlChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="invidiadbModel", Name="Resume")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Resume : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Resume object.
        /// </summary>
        /// <param name="resumeID">Initial value of the ResumeID property.</param>
        /// <param name="candidateID">Initial value of the CandidateID property.</param>
        /// <param name="fileName">Initial value of the FileName property.</param>
        public static Resume CreateResume(global::System.Int32 resumeID, global::System.Guid candidateID, global::System.String fileName)
        {
            Resume resume = new Resume();
            resume.ResumeID = resumeID;
            resume.CandidateID = candidateID;
            resume.FileName = fileName;
            return resume;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ResumeID
        {
            get
            {
                return _ResumeID;
            }
            set
            {
                if (_ResumeID != value)
                {
                    OnResumeIDChanging(value);
                    ReportPropertyChanging("ResumeID");
                    _ResumeID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ResumeID");
                    OnResumeIDChanged();
                }
            }
        }
        private global::System.Int32 _ResumeID;
        partial void OnResumeIDChanging(global::System.Int32 value);
        partial void OnResumeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid CandidateID
        {
            get
            {
                return _CandidateID;
            }
            set
            {
                OnCandidateIDChanging(value);
                ReportPropertyChanging("CandidateID");
                _CandidateID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CandidateID");
                OnCandidateIDChanged();
            }
        }
        private global::System.Guid _CandidateID;
        partial void OnCandidateIDChanging(global::System.Guid value);
        partial void OnCandidateIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FileName
        {
            get
            {
                return _FileName;
            }
            set
            {
                OnFileNameChanging(value);
                ReportPropertyChanging("FileName");
                _FileName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FileName");
                OnFileNameChanged();
            }
        }
        private global::System.String _FileName;
        partial void OnFileNameChanging(global::System.String value);
        partial void OnFileNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("invidiadbModel", "FK_ResumeContents_Resumes", "ResumeContent")]
        public ResumeContent ResumeContent
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ResumeContent>("invidiadbModel.FK_ResumeContents_Resumes", "ResumeContent").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ResumeContent>("invidiadbModel.FK_ResumeContents_Resumes", "ResumeContent").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ResumeContent> ResumeContentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ResumeContent>("invidiadbModel.FK_ResumeContents_Resumes", "ResumeContent");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ResumeContent>("invidiadbModel.FK_ResumeContents_Resumes", "ResumeContent", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="invidiadbModel", Name="ResumeContent")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ResumeContent : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ResumeContent object.
        /// </summary>
        /// <param name="resumeID">Initial value of the ResumeID property.</param>
        /// <param name="fileContent">Initial value of the FileContent property.</param>
        public static ResumeContent CreateResumeContent(global::System.Int32 resumeID, global::System.Byte[] fileContent)
        {
            ResumeContent resumeContent = new ResumeContent();
            resumeContent.ResumeID = resumeID;
            resumeContent.FileContent = fileContent;
            return resumeContent;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ResumeID
        {
            get
            {
                return _ResumeID;
            }
            set
            {
                if (_ResumeID != value)
                {
                    OnResumeIDChanging(value);
                    ReportPropertyChanging("ResumeID");
                    _ResumeID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ResumeID");
                    OnResumeIDChanged();
                }
            }
        }
        private global::System.Int32 _ResumeID;
        partial void OnResumeIDChanging(global::System.Int32 value);
        partial void OnResumeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] FileContent
        {
            get
            {
                return StructuralObject.GetValidValue(_FileContent);
            }
            set
            {
                OnFileContentChanging(value);
                ReportPropertyChanging("FileContent");
                _FileContent = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FileContent");
                OnFileContentChanged();
            }
        }
        private global::System.Byte[] _FileContent;
        partial void OnFileContentChanging(global::System.Byte[] value);
        partial void OnFileContentChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("invidiadbModel", "FK_ResumeContents_Resumes", "Resume")]
        public Resume Resume
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Resume>("invidiadbModel.FK_ResumeContents_Resumes", "Resume").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Resume>("invidiadbModel.FK_ResumeContents_Resumes", "Resume").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Resume> ResumeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Resume>("invidiadbModel.FK_ResumeContents_Resumes", "Resume");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Resume>("invidiadbModel.FK_ResumeContents_Resumes", "Resume", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="invidiadbModel", Name="Status")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Status : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Status object.
        /// </summary>
        /// <param name="statusId">Initial value of the StatusId property.</param>
        /// <param name="username">Initial value of the Username property.</param>
        /// <param name="xml">Initial value of the Xml property.</param>
        public static Status CreateStatus(global::System.Int32 statusId, global::System.String username, global::System.String xml)
        {
            Status status = new Status();
            status.StatusId = statusId;
            status.Username = username;
            status.Xml = xml;
            return status;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StatusId
        {
            get
            {
                return _StatusId;
            }
            set
            {
                if (_StatusId != value)
                {
                    OnStatusIdChanging(value);
                    ReportPropertyChanging("StatusId");
                    _StatusId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("StatusId");
                    OnStatusIdChanged();
                }
            }
        }
        private global::System.Int32 _StatusId;
        partial void OnStatusIdChanging(global::System.Int32 value);
        partial void OnStatusIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                OnUsernameChanging(value);
                ReportPropertyChanging("Username");
                _Username = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Username");
                OnUsernameChanged();
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Xml
        {
            get
            {
                return _Xml;
            }
            set
            {
                OnXmlChanging(value);
                ReportPropertyChanging("Xml");
                _Xml = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Xml");
                OnXmlChanged();
            }
        }
        private global::System.String _Xml;
        partial void OnXmlChanging(global::System.String value);
        partial void OnXmlChanged();

        #endregion
    
    }

    #endregion
    
}
