//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace iTestService
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class iTestData : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new iTestData object using the connection string found in the 'iTestData' section of the application configuration file.
        /// </summary>
        public iTestData() : base("name=iTestData", "iTestData")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new iTestData object.
        /// </summary>
        public iTestData(string connectionString) : base(connectionString, "iTestData")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new iTestData object.
        /// </summary>
        public iTestData(EntityConnection connection) : base(connection, "iTestData")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Candidate> Candidates
        {
            get
            {
                if ((_Candidates == null))
                {
                    _Candidates = base.CreateObjectSet<Candidate>("Candidates");
                }
                return _Candidates;
            }
        }
        private ObjectSet<Candidate> _Candidates;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Candidates EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCandidates(Candidate candidate)
        {
            base.AddObject("Candidates", candidate);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="iTestDataModel", Name="Candidate")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Candidate : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Candidate object.
        /// </summary>
        /// <param name="candidateID">Initial value of the CandidateID property.</param>
        public static Candidate CreateCandidate(global::System.Guid candidateID)
        {
            Candidate candidate = new Candidate();
            candidate.CandidateID = candidateID;
            return candidate;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid CandidateID
        {
            get
            {
                return _CandidateID;
            }
            set
            {
                if (_CandidateID != value)
                {
                    OnCandidateIDChanging(value);
                    ReportPropertyChanging("CandidateID");
                    _CandidateID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CandidateID");
                    OnCandidateIDChanged();
                }
            }
        }
        private global::System.Guid _CandidateID;
        partial void OnCandidateIDChanging(global::System.Guid value);
        partial void OnCandidateIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> RegistrationDate
        {
            get
            {
                return _RegistrationDate;
            }
            set
            {
                OnRegistrationDateChanging(value);
                ReportPropertyChanging("RegistrationDate");
                _RegistrationDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RegistrationDate");
                OnRegistrationDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _RegistrationDate;
        partial void OnRegistrationDateChanging(Nullable<global::System.DateTime> value);
        partial void OnRegistrationDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IdentityNumber
        {
            get
            {
                return _IdentityNumber;
            }
            set
            {
                OnIdentityNumberChanging(value);
                ReportPropertyChanging("IdentityNumber");
                _IdentityNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IdentityNumber");
                OnIdentityNumberChanged();
            }
        }
        private global::System.String _IdentityNumber;
        partial void OnIdentityNumberChanging(global::System.String value);
        partial void OnIdentityNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateOfBirth
        {
            get
            {
                return _DateOfBirth;
            }
            set
            {
                OnDateOfBirthChanging(value);
                ReportPropertyChanging("DateOfBirth");
                _DateOfBirth = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateOfBirth");
                OnDateOfBirthChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateOfBirth;
        partial void OnDateOfBirthChanging(Nullable<global::System.DateTime> value);
        partial void OnDateOfBirthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsActive;
        partial void OnIsActiveChanging(Nullable<global::System.Boolean> value);
        partial void OnIsActiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Events
        {
            get
            {
                return _Events;
            }
            set
            {
                OnEventsChanging(value);
                ReportPropertyChanging("Events");
                _Events = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Events");
                OnEventsChanged();
            }
        }
        private global::System.String _Events;
        partial void OnEventsChanging(global::System.String value);
        partial void OnEventsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ResumePath
        {
            get
            {
                return _ResumePath;
            }
            set
            {
                OnResumePathChanging(value);
                ReportPropertyChanging("ResumePath");
                _ResumePath = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ResumePath");
                OnResumePathChanged();
            }
        }
        private global::System.String _ResumePath;
        partial void OnResumePathChanging(global::System.String value);
        partial void OnResumePathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> Experience
        {
            get
            {
                return _Experience;
            }
            set
            {
                OnExperienceChanging(value);
                ReportPropertyChanging("Experience");
                _Experience = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Experience");
                OnExperienceChanged();
            }
        }
        private Nullable<global::System.Int16> _Experience;
        partial void OnExperienceChanging(Nullable<global::System.Int16> value);
        partial void OnExperienceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Areas
        {
            get
            {
                return _Areas;
            }
            set
            {
                OnAreasChanging(value);
                ReportPropertyChanging("Areas");
                _Areas = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Areas");
                OnAreasChanged();
            }
        }
        private global::System.String _Areas;
        partial void OnAreasChanging(global::System.String value);
        partial void OnAreasChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Roles
        {
            get
            {
                return _Roles;
            }
            set
            {
                OnRolesChanging(value);
                ReportPropertyChanging("Roles");
                _Roles = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Roles");
                OnRolesChanged();
            }
        }
        private global::System.String _Roles;
        partial void OnRolesChanging(global::System.String value);
        partial void OnRolesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Mobile
        {
            get
            {
                return _Mobile;
            }
            set
            {
                OnMobileChanging(value);
                ReportPropertyChanging("Mobile");
                _Mobile = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Mobile");
                OnMobileChanged();
            }
        }
        private global::System.String _Mobile;
        partial void OnMobileChanging(global::System.String value);
        partial void OnMobileChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EMailAddress
        {
            get
            {
                return _EMailAddress;
            }
            set
            {
                OnEMailAddressChanging(value);
                ReportPropertyChanging("EMailAddress");
                _EMailAddress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EMailAddress");
                OnEMailAddressChanged();
            }
        }
        private global::System.String _EMailAddress;
        partial void OnEMailAddressChanging(global::System.String value);
        partial void OnEMailAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SentToCompanies
        {
            get
            {
                return _SentToCompanies;
            }
            set
            {
                OnSentToCompaniesChanging(value);
                ReportPropertyChanging("SentToCompanies");
                _SentToCompanies = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SentToCompanies");
                OnSentToCompaniesChanged();
            }
        }
        private global::System.String _SentToCompanies;
        partial void OnSentToCompaniesChanging(global::System.String value);
        partial void OnSentToCompaniesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Former8200
        {
            get
            {
                return _Former8200;
            }
            set
            {
                OnFormer8200Changing(value);
                ReportPropertyChanging("Former8200");
                _Former8200 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Former8200");
                OnFormer8200Changed();
            }
        }
        private Nullable<global::System.Boolean> _Former8200;
        partial void OnFormer8200Changing(Nullable<global::System.Boolean> value);
        partial void OnFormer8200Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CandidateNumber
        {
            get
            {
                return _CandidateNumber;
            }
            set
            {
                OnCandidateNumberChanging(value);
                ReportPropertyChanging("CandidateNumber");
                _CandidateNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CandidateNumber");
                OnCandidateNumberChanged();
            }
        }
        private Nullable<global::System.Int32> _CandidateNumber;
        partial void OnCandidateNumberChanging(Nullable<global::System.Int32> value);
        partial void OnCandidateNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MailEntryID
        {
            get
            {
                return _MailEntryID;
            }
            set
            {
                OnMailEntryIDChanging(value);
                ReportPropertyChanging("MailEntryID");
                _MailEntryID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MailEntryID");
                OnMailEntryIDChanged();
            }
        }
        private global::System.String _MailEntryID;
        partial void OnMailEntryIDChanging(global::System.String value);
        partial void OnMailEntryIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Reference
        {
            get
            {
                return _Reference;
            }
            set
            {
                OnReferenceChanging(value);
                ReportPropertyChanging("Reference");
                _Reference = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Reference");
                OnReferenceChanged();
            }
        }
        private global::System.String _Reference;
        partial void OnReferenceChanging(global::System.String value);
        partial void OnReferenceChanged();

        #endregion
    
    }

    #endregion
    
}
